
- name: Install Sap Agent on the servers.   
  hosts: PROD
  user: vkedhari 
  become_method: sudo        
  become_user: root
  become: true
  gather_facts: true 

  environment:
    PATH: '/usr/sbin:/sbin:/usr/bin:/bin'

  tasks:
     - name:  Install SAP Agent
       command: /Media/Software_Master/SAP/Installation/SAPHostAgent/Linux/InstallHostAgent.bash NQ

...

