---
- name: sios post install 
  hosts: "{{ override_hosts | default('SIOS') }}"
  user: vkedhari
  become_method: sudo
  become_user: root
  become: true
  gather_facts: true 

  environment:
    PATH: '/usr/sbin:/sbin:/usr/bin:/bin'

  tasks:
  
  - name: unmount the IMAGE file
    mount:
      name: /mnt
      src: /tmp/sps.img
      fstype: iso9660
      opts: loop
      state: absent
  - name: Delete IMAGE file in tmp
    file: path=/tmp/sps.img.bkp state=absent
  - name: Support SCSI by default
    blockinfile:
      dest: /opt/LifeKeeper/subsys/scsi/resources/DEVNAME/device_pattern
      backup: yes
      insertafter: "/dev/fio*"
      content:  |
                  ####### Support SCSI by default:###
                  /dev/sd*
                  #########################################
  - name: Copy the license to temporary directory
    script: /home/vkedhari/ansible/ERP/playbooks/copy_licence.sh
  - name: move and restart the licence
    script: /home/vkedhari/ansible/ERP/playbooks/copy_restart.sh
  - name: Set Permission
    file: path=/var/LifeKeeper/license/ owner=root group=root mode=0700 recurse=yes
...
