---
- name: Update lkadmin group   
  hosts: "{{ override_hosts | default('ERP') }}" 
  user: vkedhari
  become_method: sudo
  become_user: root
  become: true
  gather_facts: true
  tasks:
    - name: add rmenon01 to lkadmin group
      shell: usermod -a -G lkadmin rmenon01
...
